name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install openssl ninja
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G Ninja -DKERNEL_BUILD_XNU=1 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
          ninja -t targets all
          # ninja
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: iso
      #     path: ./**/*.iso